### ISSUE TITLE
After Upgrading to 1.0.6 all REST calls fail.

### ISSUE THREAD

**Issue by ryanwkeen** [jimboca/udi-poly-notification#24]
I just upgraded to version 1.0.6.  After upgrading all of my notifications fail.  My notifications use REST calls from Network Resources.  The error that I am seeing in the log is below.  I've made no changes to my network resources, and none of them use the sound param.  Any ideas would be appreciated.  Is there a way for me to roll back to a previous version?

```
2021-06-08 03:09:31,336 Thread-1   polyinterface      ERROR    PolyglotREST:l_error: get_handler: code=500 message=ghandler failed, see log
2021-06-08 03:09:37,313 Thread-1   polyinterface      ERROR    PolyglotREST:l_error: get_handler: failed
Traceback (most recent call last):
  File "/root/.polyglot/nodeservers/Notification/PolyglotREST.py", line 253, in get_handler
    ret = self.ghandler(command,params,post_data)
  File "/root/.polyglot/nodeservers/Notification/nodes/Controller.py", line 589, in rest_ghandler
    return self.nodes[node].rest_send(data)
  File "/root/.polyglot/nodeservers/Notification/nodes/Pushover.py", line 607, in rest_send
    return self.do_send(params)
  File "/root/.polyglot/nodeservers/Notification/nodes/Pushover.py", line 492, in do_send
    params['sound'] = self.get_pushover_sound()
  File "/root/.polyglot/nodeservers/Notification/nodes/Pushover.py", line 433, in get_pushover_sound
    val = self.sounds_list[val][0]
IndexError: list index out of range
```

**Comment by jimboca** [comment]
Can you turn on debug level on the controller and try again, it will still fail but send me the log, including more lines from before the crash. 
Sorry, there is no easy way to roll back.

**Comment by ryanwkeen** [comment]
I'm sorry, I think I jumped the gun last night.  Perhaps there was some issue with Pushover.  

Today when testing everything is working and I can find no issues.  The error and timing made me believe it was a result of the update I performed just moments before.  I had performed my other normal troubleshooting steps last night but got nowhere.

Thank you for your time.

**Comment by jimboca** [comment]
No problem, glad it's fixed. It looks like pushover didn't properly respond to the NS request for the sounds list, which later caused the error. So there really is a bug that should be trapped.
