### ISSUE TITLE
No Module named 'chump'

### ISSUE THREAD

**Issue by EddieRockwell** [jimboca/udi-poly-notification#6]
Installed node server and it is seen in my ISY but shows disconnected for current status. 

I'm using Raspberry Pi with raspbian latest "Raspbian GNU/Linux 10 (buster)"

The log file:
`2019-12-14 13:05:41,681 [MainThread] [INFO ] Received Config from STDIN.
2019-12-14 13:05:41,682 [MainThread] [INFO ] UDI Polyglot v2 Interface 2.0.34 Starting...
2019-12-14 13:05:41,723 [MainThread] [ERROR] Traceback (most recent call last):
2019-12-14 13:05:41,723 [MainThread] [ERROR] File "./notification-poly.py", line 9, in <module>
2019-12-14 13:05:41,724 [MainThread] [ERROR] from nodes import Controller
2019-12-14 13:05:41,724 [MainThread] [ERROR] File "/home/pi/.polyglot/nodeservers/Notification/nodes/__init__.py", line 4, in <module>
2019-12-14 13:05:41,725 [MainThread] [ERROR] from .Pushover import Pushover
2019-12-14 13:05:41,725 [MainThread] [ERROR] File "/home/pi/.polyglot/nodeservers/Notification/nodes/Pushover.py", line 12, in <module>
2019-12-14 13:05:41,725 [MainThread] [ERROR] from chump import Application
2019-12-14 13:05:41,726 [MainThread] [ERROR] ModuleNotFoundError
2019-12-14 13:05:41,726 [MainThread] [ERROR] :
2019-12-14 13:05:41,726 [MainThread] [ERROR] No module named 'chump'`

**Comment by jimboca** [comment]
New installs will not see this issue.
